config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :titles
  resources :item_statuses
  resources :ticket_statuses
  resources :customer_statuses
  resources :user_statuses

   root 'home#index'

end

app/controllers/customer_statuses_controller.rb
class CustomerStatusesController < ApplicationController
  before_action :set_customer_status, only: [:show, :edit, :update, :destroy]

  # GET /customer_statuses
  # GET /customer_statuses.json
  def index
    @customer_statuses = CustomerStatus.all
  end

  # GET /customer_statuses/1
  # GET /customer_statuses/1.json
  def show
  end

  # GET /customer_statuses/new
  def new
    @customer_status = CustomerStatus.new
  end

  # GET /customer_statuses/1/edit
  def edit
  end

  # POST /customer_statuses
  # POST /customer_statuses.json
  def create
    @customer_status = CustomerStatus.new(customer_status_params)

    respond_to do |format|
      if @customer_status.save
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully created.' }
        format.json { render :show, status: :created, location: @customer_status }
      else
        format.html { render :new }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_statuses/1
  # PATCH/PUT /customer_statuses/1.json
  def update
    respond_to do |format|
      if @customer_status.update(customer_status_params)
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_status }
      else
        format.html { render :edit }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_statuses/1
  # DELETE /customer_statuses/1.json
  def destroy
    @customer_status.destroy
    respond_to do |format|
      format.html { redirect_to customer_statuses_url, notice: 'Customer status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_status
      @customer_status = CustomerStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_status_params
      params.require(:customer_status).permit(:description)
    end
end

app/helpers/customer_statuses_helper.rb
module CustomerStatusesHelper
end

app/views/customer_statuses/_form.html.erb
<%= form_for @customer_status, :html => { :class => "form-horizontal customer_status" } do |f| %>

  <% if @customer_status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@customer_status.errors.count, "error") %> prohibited this customer_status from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @customer_status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_statuses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/customer_statuses/edit.html.erb
<%- model_class = CustomerStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customer_statuses/index.html.erb
<%- model_class = CustomerStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customer_statuses.each do |customer_status| %>
      <tr>
        <td><%= link_to customer_status.id, customer_status_path(customer_status) %></td>
        <td><%= customer_status.description %></td>
        <td><%=l customer_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_status_path(customer_status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_status_path(customer_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_status_path,
            :class => 'btn btn-primary' %>

app/views/customer_statuses/new.html.erb
<%- model_class = CustomerStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customer_statuses/show.html.erb
<%- model_class = CustomerStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @customer_status.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              customer_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_status_path(@customer_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_status_path(@customer_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>