config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :titles
  resources :item_statuses
  resources :ticket_statuses
  resources :customer_statuses
  resources :user_statuses

   root 'home#index'

end

app/controllers/user_statuses_controller.rb
class UserStatusesController < ApplicationController
  before_action :set_user_status, only: [:show, :edit, :update, :destroy]

  # GET /user_statuses
  # GET /user_statuses.json
  def index
    @user_statuses = UserStatus.all
  end

  # GET /user_statuses/1
  # GET /user_statuses/1.json
  def show
  end

  # GET /user_statuses/new
  def new
    @user_status = UserStatus.new
  end

  # GET /user_statuses/1/edit
  def edit
  end

  # POST /user_statuses
  # POST /user_statuses.json
  def create
    @user_status = UserStatus.new(user_status_params)

    respond_to do |format|
      if @user_status.save
        format.html { redirect_to @user_status, notice: 'User status was successfully created.' }
        format.json { render :show, status: :created, location: @user_status }
      else
        format.html { render :new }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_statuses/1
  # PATCH/PUT /user_statuses/1.json
  def update
    respond_to do |format|
      if @user_status.update(user_status_params)
        format.html { redirect_to @user_status, notice: 'User status was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_status }
      else
        format.html { render :edit }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_statuses/1
  # DELETE /user_statuses/1.json
  def destroy
    @user_status.destroy
    respond_to do |format|
      format.html { redirect_to user_statuses_url, notice: 'User status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_status
      @user_status = UserStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_status_params
      params.require(:user_status).permit(:description)
    end
end

app/helpers/user_statuses_helper.rb
module UserStatusesHelper
end

app/views/user_statuses/_form.html.erb
<%= form_for @user_status, :html => { :class => "form-horizontal user_status" } do |f| %>

  <% if @user_status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user_status.errors.count, "error") %> prohibited this user_status from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user_status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_statuses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/user_statuses/edit.html.erb
<%- model_class = UserStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_statuses/index.html.erb
<%- model_class = UserStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_statuses.each do |user_status| %>
      <tr>
        <td><%= link_to user_status.id, user_status_path(user_status) %></td>
        <td><%= user_status.description %></td>
        <td><%=l user_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_status_path(user_status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_status_path(user_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_status_path,
            :class => 'btn btn-primary' %>

app/views/user_statuses/new.html.erb
<%- model_class = UserStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_statuses/show.html.erb
<%- model_class = UserStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @user_status.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              user_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_status_path(@user_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_status_path(@user_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>