config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :titles
  resources :item_statuses
  resources :ticket_statuses
  resources :customer_statuses
  resources :user_statuses

   root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_status
  belongs_to :title

  #method
  def Full_User_Name
    "#{fname} #{lname}"
  end

  def fname=(s)
    super s.titleize
  end
  def lname=(s)
    super s.titleize
  end
  def address=(s)
    super s.titleize
  end
  def city=(s)
    super s.titleize
  end

  #validation
  validates :fname, :lname, :address, :city,
            presence:true
  validates :phone,
            length: {minimum: 10, maximum: 11},
            numericality: true
  validates :fname, :lname,
            format: {with: /\A[a-zA-Z]+\z/}
  validates :city,
            length: {maximum:  22}
  validates_format_of :email,
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title_id, :user_status_id, :fname, :lname, :phone, :email, :address, :state, :city, :comment)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title_id, :class => 'control-label col-lg-2' %>
    <div class="col-sm-1">
      <%= f.collection_select :title_id,Title.all,:id,:position, {}, {class:'form-control'} %>
    </div>
    <%=f.error_span(:title_id) %>
  </div>
  <div class="form-group">
    <%= f.label :user_status_id, :class => 'control-label col-lg-2' %>
    <div class="col-sm-1">
      <%= f.collection_select :user_status_id, UserStatus.all, :id,:description, {}, {class: 'form-control'} %>
    </div>
    <%=f.error_span(:user_status_id) %>
  </div>
  <div class="form-group">
    <%= f.label :fname, 'First Name', :class => 'control-label col-lg-2' %>
    <div class="col-sm-2">
      <%= f.text_field :fname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fname) %>
  </div>
  <div class="form-group">
    <%= f.label :lname, 'Last Name', :class => 'control-label col-lg-2' %>
    <div class="col-sm-2">
      <%= f.text_field :lname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lname) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-sm-1">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-sm-3">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-sm-3">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.select :state, options_for_select(us_states, @user.state),{}, class: 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-sm-1">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group">
    <%= f.label :comment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_area :comment, :class => 'form-control' %>
    </div>
    <%=f.error_span(:comment) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to 'Create a New User', new_user_path %>
</div>
<table class="table table-striped" id="user">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title_id) %></th>
      <th><%= model_class.human_attribute_name(:user_status_id) %></th>
      <th>Name</th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.title.position %></td>
        <td><%= user.user_status.description %></td>
        <td><%= link_to user.Full_User_Name, user_path(user) %></td>
        <td><%= number_to_phone(user.phone, area_code: true) %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.state %></td>
        <td><%= user.city %></td>
        <td><%= user.comment %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title_id) %>:</strong></dt>
  <dd><%= @user.title_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_status_id) %>:</strong></dt>
  <dd><%= @user.user_status_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fname) %>:</strong></dt>
  <dd><%= @user.fname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lname) %>:</strong></dt>
  <dd><%= @user.lname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @user.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @user.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @user.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @user.comment %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>