config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :titles
  resources :item_statuses
  resources :ticket_statuses
  resources :customer_statuses
  resources :user_statuses

   root 'home#index'

end

app/controllers/ticket_statuses_controller.rb
class TicketStatusesController < ApplicationController
  before_action :set_ticket_status, only: [:show, :edit, :update, :destroy]

  # GET /ticket_statuses
  # GET /ticket_statuses.json
  def index
    @ticket_statuses = TicketStatus.all
  end

  # GET /ticket_statuses/1
  # GET /ticket_statuses/1.json
  def show
  end

  # GET /ticket_statuses/new
  def new
    @ticket_status = TicketStatus.new
  end

  # GET /ticket_statuses/1/edit
  def edit
  end

  # POST /ticket_statuses
  # POST /ticket_statuses.json
  def create
    @ticket_status = TicketStatus.new(ticket_status_params)

    respond_to do |format|
      if @ticket_status.save
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_status }
      else
        format.html { render :new }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_statuses/1
  # PATCH/PUT /ticket_statuses/1.json
  def update
    respond_to do |format|
      if @ticket_status.update(ticket_status_params)
        format.html { redirect_to @ticket_status, notice: 'Ticket status was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_status }
      else
        format.html { render :edit }
        format.json { render json: @ticket_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_statuses/1
  # DELETE /ticket_statuses/1.json
  def destroy
    @ticket_status.destroy
    respond_to do |format|
      format.html { redirect_to ticket_statuses_url, notice: 'Ticket status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_status
      @ticket_status = TicketStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_status_params
      params.require(:ticket_status).permit(:description)
    end
end

app/helpers/ticket_statuses_helper.rb
module TicketStatusesHelper
end

app/views/ticket_statuses/_form.html.erb
<%= form_for @ticket_status, :html => { :class => "form-horizontal ticket_status" } do |f| %>

  <% if @ticket_status.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@ticket_status.errors.count, "error") %> prohibited this ticket_status from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @ticket_status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ticket_statuses_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/ticket_statuses/edit.html.erb
<%- model_class = TicketStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ticket_statuses/index.html.erb
<%- model_class = TicketStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ticket_statuses.each do |ticket_status| %>
      <tr>
        <td><%= link_to ticket_status.id, ticket_status_path(ticket_status) %></td>
        <td><%= ticket_status.description %></td>
        <td><%=l ticket_status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ticket_status_path(ticket_status), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ticket_status_path(ticket_status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ticket_status_path,
            :class => 'btn btn-primary' %>

app/views/ticket_statuses/new.html.erb
<%- model_class = TicketStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ticket_statuses/show.html.erb
<%- model_class = TicketStatus -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @ticket_status.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ticket_statuses_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ticket_status_path(@ticket_status), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ticket_status_path(@ticket_status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>